{% set version = "5.0.1" %}

package:
  name: libspatialite
  version: {{ version }}

source:
  url: http://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-{{ version }}.tar.gz
  sha256: eecbc94311c78012d059ebc0fae86ea5ef6eecb13303e6e82b3753c1b3409e98
  patches:
    # Skips 3 tests (check_extension, check_sql_stmt, and check_get_normal_zoom_extension_load) that are failing on OS X.
    # Re-visit this once a new release is out.
    - skip_failing_test.patch  # [osx]
    - makefile.vc.patch  # [win]
    - config-msvc.patch  # [win]
    - gg_extras.patch  # [win]
    - proj_api.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    # No idea.  Staying with minor version pin.
    - {{ pin_subpackage('libspatialite', max_pin='x.x') }}

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool   # [unix]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
  host:
    - libiconv  # [osx]
    - sqlite
    - geos
    - proj <8.0.0  # proj_api.h header is removed in newer versions
    - freexl
    - zlib
    - libxml2
  run:
    - libiconv  # [osx]
    - sqlite
    - geos
    - proj <8.0.0  # proj_api.h header is removed in newer versions
    - freexl
    - zlib
    - libxml2

about:
  home: https://www.gaia-gis.it/fossil/libspatialite/index
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Extend the SQLite core to support fully fledged Spatial SQL capabilities'

extra:
  recipe-maintainers:
    - danclewley
    - gillins
    - ocefpaf
