travis:
  secure:
    BINSTAR_TOKEN: l6u40uJCu/TX2CTLCtkdh+rKgQJlY1NIDKR4P9BFaoK2zRAmcwbXdUQ+DQMr7JwsEmyv1xeDie8JDHPtPSL91a4+bQBYjrOYRjvi2ORbwAzcNJb/d1nJ/27iiclszEqL7Pu1F1abUw+isS0RYkDYoR+GW18Q0YyH3p1yxBL1p7uqPmbnAmaK117nkSIsxSewSdae8ExYo3xV3XUgUgVU8aS9VbG5e4+QdzAxOkg0b5e7WNAIIYsQcfSzj73YquPWTM89wpzQFx27A9MH8mi1LbQsaI4esdQmk+uRg8zjIwHpd+8u1u/XJTPgULPjs22i+GCOzSgDPVKY+/lkJhQ89Lz3Grju6BaIP4r4r5LvTygftYVxybOtanqHaaZ1gb+1fR2XFsARMGH9wxj3abARLM07JBxIxvkpsibvXG1aZYu2ey1wCJya3DlP1gLiRa56vhOAlzvD+p7/JPD5sED3sGvGYivZUc1ssN9KuZyk0ySHIBzaeogfynTQ9oCLY8OFJAeX3wlaxwYbSNvy8pMLvEpl9xyYEMy+l8oZPi343peoLv/XBzDFvldyBHndYPXonNygSi+gTUpTs3rPoAjzQmkWyO68TpbzHcY2Qx0yf5zO/Wz9m/PRnrfjYsbvRBNmu9WCHL2EzhroGT4aq06Bs//LjBsNYqaSzOtHcOL/PM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
